create database empleados;
USE empleados;

CREATE TABLE CONTRATO
(
   ID_CONTRATO int AUTO_INCREMENT PRIMARY KEY NOT NULL,
   NOMBRE varchar (100) NOT NULL
);

CREATE TABLE EMPLEADO
(
   ID_EMPLEADO int AUTO_INCREMENT PRIMARY KEY NOT NULL,
   CVE_EMPLEADO varchar (15) NOT NULL,
   NOMBRE varchar (50),
   PATERNO varchar (100),
   MATERNO varchar (100),
   ID_CONTRATO int,
   CONSTRAINT CLAVE_EMPLEADO_CONSTRAINT UNIQUE(CVE_EMPLEADO),
   CONSTRAINT FK_CONTRATO_ FOREIGN KEY (ID_CONTRATO) REFERENCES CONTRATO (ID_CONTRATO)
);

CREATE TABLE AREA
(
   CVE_AREA varchar (15) NOT NULL PRIMARY KEY,
   DESCRIPCION varchar (100),
   CONSTRAINT CLAVE_AREA_CONSTRAINT UNIQUE(CVE_AREA)
);

CREATE TABLE EMPLEADO_AREA
(
   ID_EMPLEADO int NOT NULL,
   CVE_AREA varchar (15) NOT NULL,
   PRIMARY KEY (ID_EMPLEADO, CVE_AREA),
   CONSTRAINT FK_EMPLEADO_AREA_EMP FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADO (ID_EMPLEADO),
   CONSTRAINT FK_EMPLEADO_AREA_ARE FOREIGN KEY (CVE_AREA) REFERENCES AREA (CVE_AREA)
);